### ISSUE TITLE
CI: more inclusive pydarshan paths

### ISSUE THREAD

**Issue by tylerjereddy** [darshan-hpc/darshan#795]
The current `pydarshan` CI testing has `paths` triggers that are too restrictive (see below). Case in point, if you change the CI configuration in the `.github/workflows/main_ci.yml` file, it should rerun the CI steps specified in that `yml` file, otherwise there is no sane way for a reviewer to consider the correctness of the CI configuration changes in practice.

```yml
name: Python Testing

on:
  push:
    branches:
      - main
    paths:
      - darshan-util/**
      - include/**
  pull_request:
    branches:
      - main
    paths:
      - darshan-util/**
      - include/**
```
